apiVersion: apps/v1
kind: Deployment
metadata:
  name: workwave-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workwave
  template:
    metadata:
      labels:
        app: workwave
    spec:
      containers:
        - name: workwave-container
          image: samuelafolabi/workwave:v1
          ports:
            - containerPort: 80
